service: serveless-aws-node-api-local

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  memorySize: 256
  stage: ${opt:stage, 'local'}
  environment:
    DB_HOST: ${file(./config.${opt:stage, 'dev'}.json):dbHost}
    DB_DATABASE: ${file(./config.${opt:stage, 'dev'}.json):dataBase}
    DB_PORT: ${file(./config.${opt:stage, 'dev'}.json):dbPort}
    DB_USERNAME: ${file(./config.${opt:stage, 'dev'}.json):userName}
    DB_PASSWORD: ${file(./config.${opt:stage, 'dev'}.json):dbPassword}

functions:
  createBook:
    handler: src/Books.createBook
    events:
      - http:
          path: books
          method: post
  listBooks:
    handler: src/Books.listBooks
    events:
      - http:
          path: books
          method: get
  listBook:
    handler: src/Books.listBook
    events:
      - http:
          path: books/{id}
          method: get
  deleteBook:
    handler: src/Books.deleteBook
    events:
      - http:
          path: books/{id}
          method: delete

plugins:
  - serverless-offline
  - serverless-plugin-typescript

package:
  excludeDevDependencies: true
  include: src/**!(*spec).js

custom:
  serverless-offline:
    host: 0.0.0.0
