service: serveless-aws-node-api-local

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  memorySize: 256

functions:
  createBook:
    handler: src/Books.createBook
    events:
      - http:
          path: books
          method: post
  listBooks:
    handler: src/Books.listBooks
    events:
      - http:
          path: books
          method: get
  listBook:
    handler: src/Books.listBook
    events:
      - http:
          path: books/{id}
          method: get
  deleteBook:
    handler: src/Books.deleteBook
    events:
      - http:
          path: books/{id}
          method: delete

plugins:
  - serverless-offline
  - serverless-plugin-typescript

package:
  excludeDevDependencies: true
  include: src/**!(*spec).js
