service: serveless-aws-node-api-local

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  memorySize: 256

functions:
  create:
    handler: src/Books.create
    events:
      - http:
          path: books
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript
